name: CI
on:
  push:
    branches:
      - use-express-backend
env:
  CI: true
  NODE_ENV: test

jobs:
  webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-webapp-${{ hashFiles('webapp/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-webapp-

      - name: Install dependencies
        run: cd webapp && npm ci
      - name: Lint
        run: cd webapp && npm run lint
      - name: Tests
        run: cd webapp && npm run test

  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-server-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-server-
      - name: Pull Docker images and cache
        run: docker compose pull
      - uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Start Postgres and Firebase emulator
        run: docker compose up -d
      - name: Install dependencies
        run: cd server && npm ci
      - name: Lint
        run: cd server && npm run lint
      - name: Tests
        run: cd server && npm run test
